title: sysbio
email: admin@sysbio.org.ua
description: >- # this means to ignore newlines until "baseurl:"
 Systems Biology lab at IMBG, Kyiv, Ukraine.
baseurl: # the subpath of your site, e.g. /blog
url: https://sysbio.org.ua # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sysbio-vo
github_username:  sysbio-vo

languages: ["en", "ua"]
default_lang: "en"
active_lang: "en"
#exclude_from_localization: ["assets/img"]
parallel_localization: true

collections:
  projects:
    output: true
    permalink: /projects/:title.markdown
  members:
    output: true
    permalink: /members/:title.markdown
  tools:
    output: true
    permalink: /tools/:title.markdown

# Build settings
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-scholar

scholar:
  sort_by: year
  order: descending
  bibliography: sysbio_publications.bib
  style: _bibliography/my-mla.csl

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
