menu:
  en:
    - {name: 'Home', url: ''}
    - {name: 'Research',  url: 'research'}
    - {name: 'Publications',  url: 'publications'}
    - {name: 'Tools',  url: 'tools'}
    - {name: 'Team',  url: 'team'}
    - {name: 'Opportunities',  url: 'opportunities'}
    - {name: 'Blog',  url: 'blog'}
    - {name: 'Contacts',  url: 'contacts'}
    - {name: 'Support us', focus: true, url: 'support'}
  ua:
    - { name: 'Головна', url: '' }
    - { name: 'Дослідження',  url: 'research' }
    - { name: 'Публікації',  url: 'publications' }
    - { name: 'Застосунки',  url: 'tools' }
    - { name: 'Команда',  url: 'team' }
    - { name: 'Можливості',  url: 'opportunities' }
    - { name: 'Контакти',  url: 'contacts' }
    - { name: 'Блог',  url: 'blog' }
    - { name: 'Підтримати нас', focus: true, url: 'support' }

social:
- {icon: 'youtube', link:   'https://www.youtube.com/channel/UCnhV3Xbdc2nSqTiGSZ4nbOA'}
- {icon: 'linkedin', link:  'https://www.linkedin.com/company/sysbioua'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
