menu:
- {name: 'Projects',  url: 'projects'}
- {name: 'Contacts',  url: 'contacts'}

social:
- {icon: 'twitter', link:    'https://twitter.com/paululele'}
- {icon: 'instagram', link:  'https://instagram.com/paululele'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
